openapi: 3.0.3
info:
  title: AI-Sommelier Auth API
  description: API для регистрации и авторизации пользователей
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

paths:
  /auth/register:
    post:
      summary: Регистрация нового пользователя
      operationId: register
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          headers:
            Set-Cookie:
              description: JWT токен в HttpOnly cookie
              schema:
                type: string
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Превышен лимит запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      summary: Вход в систему
      operationId: login
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          headers:
            Set-Cookie:
              description: JWT токен в HttpOnly cookie
              schema:
                type: string
        '401':
          description: Неверные учётные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Превышен лимит попыток входа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitResponse'

  /auth/logout:
    post:
      summary: Выход из системы
      operationId: logout
      tags:
        - auth
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Успешный выход
          headers:
            Set-Cookie:
              description: Удаление cookie
              schema:
                type: string
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/me:
    get:
      summary: Получить текущего пользователя
      operationId: getCurrentUser
      tags:
        - auth
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/password-reset/request:
    post:
      summary: Запрос сброса пароля
      operationId: requestPasswordReset
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetRequest'
      responses:
        '200':
          description: |
            Если email существует, письмо отправлено.
            Ответ всегда одинаковый для защиты от перебора.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '429':
          description: Превышен лимит запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/password-reset/confirm:
    post:
      summary: Подтверждение сброса пароля
      operationId: confirmPasswordReset
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetConfirm'
      responses:
        '200':
          description: Пароль успешно изменён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Невалидный или истёкший токен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token

  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
        - is_age_verified
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          minLength: 8
          example: "securepassword123"
        is_age_verified:
          type: boolean
          description: Подтверждение возраста 18+
          example: true

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          example: "securepassword123"

    PasswordResetRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          example: user@example.com

    PasswordResetConfirm:
      type: object
      required:
        - token
        - new_password
      properties:
        token:
          type: string
          description: Токен из email
          example: "abc123def456..."
        new_password:
          type: string
          minLength: 8
          example: "newsecurepassword123"

    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        email:
          type: string
          format: email
          example: user@example.com
        is_age_verified:
          type: boolean
          example: true
        created_at:
          type: string
          format: date-time
          example: "2026-02-02T12:00:00Z"

    MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: "Если email существует, письмо отправлено"

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          example: "Неверный email или пароль"

    RateLimitResponse:
      type: object
      properties:
        detail:
          type: string
          example: "Превышен лимит попыток входа"
        retry_after:
          type: integer
          description: Секунд до разблокировки
          example: 900
